version: '3.8'

services:
  web:
    image: yanyanjymv/yanyan-jymv:01  # Image sudah dibuild & push ke Docker Hub
    ports:
      - "9090:80"  # Akses web melalui localhost:9090
    depends_on:
      - db  # Pastikan database siap sebelum PHP mengakses
    environment:
      DB_HOST: db
      DB_NAME: alimrugi
      DB_USER: root
      DB_PASSWORD: 1234

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alimrugi
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234

volumes:
  mysql-data:
