services:
  # Service untuk Nginx yang melayani aplikasi PHP dan PHP-FPM
  web:
    image: yanyanjymv/yanyan-jymv:01  # Menggunakan image yang sudah dibangun di Docker Hub
    ports:
      - "9090:80"  # Nginx akan mendengarkan di port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mengonfigurasi Nginx
      - ./html:/usr/share/nginx/html
    depends_on:
      - "php"
      - "db"  
    networks:
      - app-network

  php:
    image: php:-fpm  # Gunakan image PHP-FPM
    volumes:
      - ./html:/usr/share/nginx/html  # Menyalin aplikasi PHP ke container PHP
    entrypoint: |
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql json && php-fpm"
    networks:
      - app-network

  # Service untuk MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alimrugi
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
