version: '3.8'
services:
  # Service untuk Nginx yang melayani aplikasi PHP dan PHP-FPM
  web:
    image: yanyanjymv/yanyan-jymv:01  # Menggunakan image yang sudah dibangun di Docker Hub
    ports:
      - "9090:80"  # Nginx akan mendengarkan di port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mengonfigurasi Nginx
      - ./html:/usr/share/nginx/html
    depends_on:
      - "php"
      - "db"  
    networks:
      - app-network
    


  php:
    build:
      context: .  # Menunjukkan bahwa Dockerfile berada di direktori saat ini
      dockerfile: Dockerfile.php  # Nama Dockerfile untuk PHP
    networks:
      - app-networkn:
      - "db"

  # Service untuk MySQL
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alimrugi
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
