name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: appleboy/scp-action@v1
        with:
          username: ${{ secrets.AWS_USERNAME }}
          host: ${{ secrets.AWS_HOST }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: |
            DOCKER/*
                  
          target: "/home/${{ secrets.AWS_USERNAME }}/DOCKER/"

      - name: Run deployment script on AWS 
        uses: appleboy/ssh-action@v1
        with:
          username: ${{ secrets.AWS_USERNAME }}
          host: ${{ secrets.AWS_HOST }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USERNAME }}/DOCKER/
            docker pull ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv:01 
            docker-compose down
            docker-compose up -d
             