name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Deploy using scp to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }} 
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.AWS_USERNAME }}/DOCKER/"

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: | 
            cd DOCKER
            docker-compose down
            docker image prune -a -f
            docker-compose up -d
            