name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Deploy using SCP to AWS
        uses: appleboy/ssh-action@v1
        with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          scp -i ${{ secrets.AWS_PRIVATE_KEY }} -r ./docker-compose.yml ./Dockerfile.php ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USERNAME }}/DOCKER/

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USERNAME }}/DOCKER/
            docker pull ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv:01 
            docker-compose down
            docker-compose up -d
            