name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build PHP Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv -f php/Dockerfile .
          
      - name: Build Nginx Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv -f nginx/Dockerfile .

      - name: Docker Metadata for Images
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv
            ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv
          flavor: |
            latest=false
          tags: |
            type=raw,value=01

      - name: Push PHP Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv:02

      - name: Push Nginx Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/yanyan-jymv:01
