name: Build and Push Docker Image

on:
 push:
   branches:
     - main
 pull_request:
      -main

jobs:
 build-image:
   name: Build and Push Docker Image
   runs-on: ubuntu-latest
    
   steps:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
        
     - name: Docker Metadata for Image
       id: docker_meta
       uses: docker/metadata-action@v5
       with:
         images: yanyanjymv/yanyan-jymv
         flavor: |
           latest=false
         tags: |
           type=raw,value=01

     - name: Build and Push to Docker Hub
       id: docker_build
       uses: docker/build-push-action@v5
       with:
         push: true
         tags: ${{ steps.docker_meta.outputs.tags }}
         labels: ${{ steps.docker_meta.outputs.labels }}
         cache-from: type=gha
         cache-to: type=gha,mode=max
         platforms: linux/amd64
